mediatek/task_turbo: set_load_weight() must also call reweight_task() for SCHED_IDLE tasks
- Commit [1] has fundamentally changed how set_load_weight() works.
- Hence, this caused the following build error:

/home/ubuntu/kernel/kernel-5.10/drivers/misc/mediatek/task_turbo/task_turbo.c:592:20: error: incompatible integer to pointer conversion passing 'int'
 to parameter of type 'const struct load_weight *' [-Werror,-Wint-conversion]
                reweight_task(p, prio);
                                 ^~~~
/home/ubuntu/kernel/kernel-5.10/kernel/sched/sched.h:1996:76: note: passing argument to parameter 'lw' here
extern void reweight_task(struct task_struct *p, const struct load_weight *lw);
                                                                           ^
1 error generated.

- Fix it by updating reweight_task() to take struct load_weight as idle weight can't be expressed with prio and making set_load_weight() call reweight_task() for SCHED_IDLE tasks too when @update_load is set.

[1]: https://android.googlesource.com/kernel/common/+/cf0c713c6946413b712c2311c6666d11a73ae4c2

Change-Id: I8282faf4d81f5e7eaf52d1e192b44e67afd34c27
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>